server:
  port: 8082

spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  application:
    name: smart-event-driven-examples
  profiles:
    active: DEV

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306?autoReconnect=true&allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: root
      initial-size: 50
      max-active: 200
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
      filters: config,stat,slf4j

smart:
  event-driven:
    rocketmq:
      name-server: 10.251.76.2:9876;10.251.76.3:9876;10.251.76.4:9876;10.251.76.5:9876 # 10.251.64.105:9876;10.251.64.130:9876;10.251.64.80:9876;10.251.64.53:9876
      namespace: noah-ns
      publishable-notifier-topic: ${spring.application.name}-publishable-notifier
      consumer:
        enabled: true
      producer:
        group: ${spring.application.name}-producer-group

swagger.enabled: true
swagger.title: 事件驱动组件样例
swagger.description: 事件驱动组件样例
swagger.version: v0.0.1
swagger.base-package: org.smartframework.event.driven.examples
swagger.base-path: /**
swagger.exclude-path: /error, /ops/**

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.alibaba.druid.pool: ERROR
